version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6

    working_directory: ~/pyls

    environment:
        PYTHON_VERSION: "3.6"
        OPENBLAS_NUM_THREADS: "1"
        MKL_NUM_THREADS: "1"

    steps:
      - checkout
      - restore_cache:
          name: Restoring data cache
          keys:
            - data-v1-{{ .Branch }}
            - data-v1-
      - run:
          name: Downloading Matlab PLS results
          command: |
            if [[ -e /tmp/data/matlab ]]; then
              echo "Restoring Matlab PLS results from cache"
            else
                mkdir -p /tmp/data/matlab
                curl -L https://www.dropbox.com/s/8h1fpq194022y50/matpls.tar.gz?dl=1 | tar xz -C /tmp/data/matlab
            fi
      - save_cache:
          name: Caching Matlab PLS results
          key: data-v1-{{ .Branch }}
          paths:
            - /tmp/data
      - restore_cache:
          name: Restoring dependencies cache
          keys:
            - dependencies-v1-{{ checksum "requirements.txt" }}
            - dependencies-v1-
      - run:
          name: Creating test environment
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install .[tests]
      - save_cache:
          name: Caching dependencies
          key: dependencies-v1-{{ checksum "requirements.txt" }}
          paths:
            - ./venv
      - run:
          name: Running Matlab-Python comparison
          no_output_timeout: 40m
          command: |
            . venv/bin/activate
            for mat in /tmp/data/matlab/*mat; do
              printf "${mat} "
              python -c "import pyls.tests.test_matlab_comp; pyls.tests.test_matlab_comp.test_matlab_comparison('${mat}');"
            done
